# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.

title: "Lantern Properties"
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: "/:categories/:year/:month/:day/:title:output_ext"

# Build settings
theme: minima
plugins:
  - jekyll-feed
